// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3mboq7wSi2OKYhVeWuEac2G1RcKIjy8g',
    appId: '1:309557428741:web:780bacede6e05db6e3526c',
    messagingSenderId: '309557428741',
    projectId: 'atsave-29469',
    authDomain: 'atsave-29469.firebaseapp.com',
    storageBucket: 'atsave-29469.appspot.com',
    measurementId: 'G-V5QLM3GGCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuaZ3IgEDwg2sk-UJXqsaR23xGmeQGHao',
    appId: '1:309557428741:android:01503f82817b2abee3526c',
    messagingSenderId: '309557428741',
    projectId: 'atsave-29469',
    storageBucket: 'atsave-29469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1b5T_4raZhhEN_87gPjZQq_Xpeq5VLps',
    appId: '1:309557428741:ios:a484a553a7cd88e7e3526c',
    messagingSenderId: '309557428741',
    projectId: 'atsave-29469',
    storageBucket: 'atsave-29469.appspot.com',
    iosClientId: '309557428741-lj40n8i0tf0no29g5elir36sslpoe01k.apps.googleusercontent.com',
    iosBundleId: 'com.example.atSave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1b5T_4raZhhEN_87gPjZQq_Xpeq5VLps',
    appId: '1:309557428741:ios:d18a4549469b7aa3e3526c',
    messagingSenderId: '309557428741',
    projectId: 'atsave-29469',
    storageBucket: 'atsave-29469.appspot.com',
    iosClientId: '309557428741-fp19gjhlp5hqrq75jcc7u638mbujlb92.apps.googleusercontent.com',
    iosBundleId: 'com.example.atSave.RunnerTests',
  );
}
